# Generated by Django 4.1.5 on 2023-01-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('genre', models.CharField(max_length=75)),
                ('description', models.TextField(max_length=250)),
                ('author', models.CharField(max_length=75)),
            ],
        ),
    ]
