# Generated by Django 4.1.5 on 2023-01-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_opinion'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='thoughts',
            field=models.TextField(default='default', max_length=250),
            preserve_default=False,
        ),
    ]
